DB_PATH = "data/basecamp.db"
CSI_UDP_PORT = 5006
CSI_UDP_HOST = "0.0.0.0"
AUDIO_SAMPLE_RATE = 16000
AUDIO_CHUNK_SECONDS = 30
SILENCE_THRESHOLD = 0.01
SNORE_THRESHOLD = 0.05
SNORE_FREQ_LOW = 60
SNORE_FREQ_HIGH = 500
RADAR_SERIAL_PORT = "/dev/ttyAMA0"
RADAR_BAUD_RATE = 256000
MIN_SLEEP_HOURS = 4
I2C_BUS = 1
SHT40_ADDR = 0x44
BH1750_ADDR = 0x23
SCD40_ADDR = 0x62
SGP40_ADDR = 0x59
NTFY_TOPIC = "basecamp-recovery"
NTFY_SERVER = "https://ntfy.sh"
RECOVERY_WEIGHTS = {
    "architecture": 0.40,
    "continuity": 0.25,
    "breathing": 0.20,
    "environment": 0.15,
}

MOCK_HARDWARE = True

# Screen and button GPIO
SCREEN_BACKLIGHT_PIN = 22   # GPIO 22 (GPIO 24 is SPI DC — conflicts with touchscreen)
BUTTON_PIN = 26

# Sleep mode timing
BEDTIME_WINDOW_START = 21
BEDTIME_WINDOW_END = 0
PRESENCE_ARM_MINUTES = 2
BEDTIME_PROMPT_TIMEOUT_MINUTES = 5
BEDTIME_SNOOZE_MINUTES = 30
AUTO_RECORD_MINUTES = 15
WAKE_ABSENCE_MINUTES = 15
WAKE_EARLIEST_HOUR = 5

# Pipeline / model
ANOMALY_MIN_NIGHTS = 60
AUDIO_RETENTION_DAYS = 7

# Watchdog / health
WATCHDOG_INTERVAL_SECONDS = 30
HEARTBEAT_INTERVAL_SECONDS = 60
